version: '3.8'
services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"  
    depends_on:
      - node-service
    networks:
      - app-network

  node-service:
    build: ./api
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: 12345 
      DB_DATABASE: database
    depends_on:
      - db
    networks:
      - app-network

  db:
    build: ./db
    environment:
      MYSQL_ROOT_PASSWORD: 12345  
      MYSQL_DATABASE: database
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:

volumes:
  db-data:
